/* 
USE [DB????]
GO
*/

/**************************************************************************************/
/****** Remove tables *****************************************************************/
/****** Object:  Table [dbo].[BORROW]    Script Date: 2014-08-25 15:18:34 ******/
ALTER TABLE [dbo].[BORROW] DROP CONSTRAINT [FK_BORROW_COPY]
GO

ALTER TABLE [dbo].[BORROW] DROP CONSTRAINT [FK_BORROW_BORROWER]
GO

DROP TABLE [dbo].[BORROW]
GO

/****** Object:  Table [dbo].[BORROWER]    Script Date: 2014-08-25 15:20:47 ******/
ALTER TABLE [dbo].[BORROWER] DROP CONSTRAINT [FK_BORROWER_CATEGORY]
GO

DROP TABLE [dbo].[BORROWER]
GO

/****** Object:  Table [dbo].[CATEGORY]    Script Date: 2014-08-25 15:22:02 ******/
DROP TABLE [dbo].[CATEGORY]
GO

/****** Object:  Table [dbo].[COPY]    Script Date: 2014-08-25 15:23:52 **********/
ALTER TABLE [dbo].[COPY] DROP CONSTRAINT [FK_COPY_STATUS]
GO

ALTER TABLE [dbo].[COPY] DROP CONSTRAINT [FK_COPY_BOOK]
GO

DROP TABLE [dbo].[COPY]
GO

/****** Object:  Table [dbo].[STATUS]    Script Date: 2014-08-25 15:24:36 ******/
DROP TABLE [dbo].[STATUS]
GO

/****** Object:  Table [dbo].[BOOK_AUTHOR]    Script Date: 2014-08-25 15:25:54 ******/
ALTER TABLE [dbo].[BOOK_AUTHOR] DROP CONSTRAINT [FK_BOOK_AUTHOR_BOOK]
GO

ALTER TABLE [dbo].[BOOK_AUTHOR] DROP CONSTRAINT [FK_BOOK_AUTHOR_AUTHOR]
GO

DROP TABLE [dbo].[BOOK_AUTHOR]
GO

/****** Object:  Table [dbo].[AUTHOR]    Script Date: 2014-08-25 15:27:41 ******/
DROP TABLE [dbo].[AUTHOR]
GO

/****** Object:  Table [dbo].[BOOK]    Script Date: 2014-08-25 15:28:14 ******/
ALTER TABLE [dbo].[BOOK] DROP CONSTRAINT [FK_BOOK_PUBLISHER]
GO

ALTER TABLE [dbo].[BOOK] DROP CONSTRAINT [FK_BOOK_CLASSIFICATION]
GO

DROP TABLE [dbo].[BOOK]
GO

/****** Object:  Table [dbo].[PUBLISHER]    Script Date: 2014-08-25 15:29:44 ******/
DROP TABLE [dbo].[PUBLISHER]
GO

/****** Object:  Table [dbo].[CLASSIFICATION]    Script Date: 2014-08-25 15:28:58 ******/
DROP TABLE [dbo].[CLASSIFICATION]
GO



/**************************************************************************************/
/****** Create tables *****************************************************************/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[PUBLISHER]    Script Date: 2014-08-25 15:29:44 ******/
CREATE TABLE [dbo].[PUBLISHER](
	[PublisherId] [nvarchar](10) NOT NULL,
	[PublisherName] [nvarchar](50) NULL,
 CONSTRAINT [PK_PUBLISHER] PRIMARY KEY CLUSTERED 
(
	[PublisherId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[CLASSIFICATION]    Script Date: 2014-08-25 15:28:58 ******/
CREATE TABLE [dbo].[CLASSIFICATION](
	[SignId] [int] NOT NULL,
	[Signum] [nvarchar](50) NULL,
	[Description] [nvarchar](255) NULL,
 CONSTRAINT [PK_CLASSIFICATION] PRIMARY KEY CLUSTERED 
(
	[SignId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[BOOK]    Script Date: 2014-08-25 15:28:14 ******/
CREATE TABLE [dbo].[BOOK](
	[ISBN] [nvarchar](15) NOT NULL,
	[Title] [nvarchar](255) NULL,
	[SignId] [int] NULL,
	[PublicationYear] [nvarchar](10) NULL,
	[Publisher] [nvarchar](10) NULL,
	[LibNo] [int] NULL,
 CONSTRAINT [PK_BOOK] PRIMARY KEY CLUSTERED 
(
	[ISBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD  CONSTRAINT [FK_BOOK_CLASSIFICATION] FOREIGN KEY([SignId])
REFERENCES [dbo].[CLASSIFICATION] ([SignId])
GO

ALTER TABLE [dbo].[BOOK] CHECK CONSTRAINT [FK_BOOK_CLASSIFICATION]
GO

ALTER TABLE [dbo].[BOOK]  WITH CHECK ADD  CONSTRAINT [FK_BOOK_PUBLISHER] FOREIGN KEY([Publisher])
REFERENCES [dbo].[PUBLISHER] ([PublisherId])
GO

ALTER TABLE [dbo].[BOOK] CHECK CONSTRAINT [FK_BOOK_PUBLISHER]
GO

/****** Object:  Table [dbo].[AUTHOR]    Script Date: 2014-08-25 15:27:41 ******/
CREATE TABLE [dbo].[AUTHOR](
	[Aid] [int] NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[BirthYear] [nvarchar](10) NULL,
 CONSTRAINT [PK_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[Aid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[BOOK_AUTHOR]    Script Date: 2014-08-25 15:25:54 ******/
CREATE TABLE [dbo].[BOOK_AUTHOR](
	[ISBN] [nvarchar](15) NOT NULL,
	[Aid] [int] NOT NULL,
 CONSTRAINT [PK_BOOK_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[ISBN] ASC,
	[Aid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BOOK_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_BOOK_AUTHOR_AUTHOR] FOREIGN KEY([Aid])
REFERENCES [dbo].[AUTHOR] ([Aid])
GO

ALTER TABLE [dbo].[BOOK_AUTHOR] CHECK CONSTRAINT [FK_BOOK_AUTHOR_AUTHOR]
GO

ALTER TABLE [dbo].[BOOK_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_BOOK_AUTHOR_BOOK] FOREIGN KEY([ISBN])
REFERENCES [dbo].[BOOK] ([ISBN])
GO

ALTER TABLE [dbo].[BOOK_AUTHOR] CHECK CONSTRAINT [FK_BOOK_AUTHOR_BOOK]
GO

/****** Object:  Table [dbo].[STATUS]    Script Date: 2014-08-25 15:24:36 ******/
CREATE TABLE [dbo].[STATUS](
	[statusid] [int] NOT NULL,
	[status] [nvarchar](50) NULL,
 CONSTRAINT [PK_STATUS] PRIMARY KEY CLUSTERED 
(
	[statusid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[COPY]    Script Date: 2014-08-25 15:23:52 ******/
CREATE TABLE [dbo].[COPY](
	[Barcode] [nvarchar](20) NOT NULL,
	[Location] [nvarchar](50) NULL,
	[StatusId] [int] NULL,
	[ISBN] [nvarchar](15) NULL,
 CONSTRAINT [PK_COPY] PRIMARY KEY CLUSTERED 
(
	[Barcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[COPY]  WITH CHECK ADD  CONSTRAINT [FK_COPY_BOOK] FOREIGN KEY([ISBN])
REFERENCES [dbo].[BOOK] ([ISBN])
GO

ALTER TABLE [dbo].[COPY] CHECK CONSTRAINT [FK_COPY_BOOK]
GO

ALTER TABLE [dbo].[COPY]  WITH CHECK ADD  CONSTRAINT [FK_COPY_STATUS] FOREIGN KEY([StatusId])
REFERENCES [dbo].[STATUS] ([statusid])
GO

ALTER TABLE [dbo].[COPY] CHECK CONSTRAINT [FK_COPY_STATUS]


/****** Object:  Table [dbo].[CATEGORY]    Script Date: 2014-08-25 15:22:02 ******/

CREATE TABLE [dbo].[CATEGORY](
	[CatergoryId] [int] NOT NULL,
	[Category] [nvarchar](50) NULL,
	[Period] [smallint] NULL,
	[Penaltyperday] [int] NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CatergoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[BORROWER]    Script Date: 2014-08-25 15:20:47 ******/
CREATE TABLE [dbo].[BORROWER](
	[PersonId] [nvarchar](13) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
	[Telno] [nvarchar](50) NULL,
	[CategoryId] [int] NULL,
 CONSTRAINT [PK_BORROWER] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BORROWER]  WITH CHECK ADD  CONSTRAINT [FK_BORROWER_CATEGORY] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[CATEGORY] ([CatergoryId])
GO

ALTER TABLE [dbo].[BORROWER] CHECK CONSTRAINT [FK_BORROWER_CATEGORY]
GO

/****** Object:  Table [dbo].[BORROW]    Create Script Date: 2014-08-25 15:18:34 ******/
CREATE TABLE [dbo].[BORROW](
	[Barcode] [nvarchar](20) NOT NULL,
	[PersonId] [nvarchar](13) NOT NULL,
	[BorrowDate] [datetime] NOT NULL,
	[ToBeReturnedDate] [datetime] NULL,
	[ReturnDate] [datetime] NULL,
 CONSTRAINT [PK_BORROW] PRIMARY KEY CLUSTERED 
(
	[Barcode] ASC,
	[PersonId] ASC,
	[BorrowDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BORROW]  WITH CHECK ADD  CONSTRAINT [FK_BORROW_BORROWER] FOREIGN KEY([PersonId])
REFERENCES [dbo].[BORROWER] ([PersonId])
GO

ALTER TABLE [dbo].[BORROW] CHECK CONSTRAINT [FK_BORROW_BORROWER]
GO

ALTER TABLE [dbo].[BORROW]  WITH CHECK ADD  CONSTRAINT [FK_BORROW_COPY] FOREIGN KEY([Barcode])
REFERENCES [dbo].[COPY] ([Barcode])
GO

ALTER TABLE [dbo].[BORROW] CHECK CONSTRAINT [FK_BORROW_COPY]
GO


